# There are multiple packages and for each package we might have
# unit, integration and e2e tests
#
# If we can control only a single variable, and it should be our command
env:
  - CMD="test -- --package packages/coffee/"
  - CMD="test -- --package packages/desktop-gui/"
  # TODO fix driver tests
  - CMD="test -- --package packages/electron/"
  # TODO clarify unit vs E2E tests in example project
  - CMD="test -- --package packages/extension/"
  - CMD="test -- --package packages/https-proxy/"
  - CMD="test -- --package packages/launcher/"
  - CMD="test -- --package packages/reporter/"
  - CMD="test -- --package packages/runner/"
  # TODO fix server tests
  - CMD="test -- --package packages/socket/"
  - CMD="test -- --package packages/static/"

command:
  - echo "Running $CMD"
  - npm run all $CMD
