version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  build:
    executor:
      name: node/default
      tag: '12'

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Yarn install
                command: yarn install --frozen-lockfile
      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: Cypress Verfiy
          command: $(npm bin)/cypress verify
      - run:
          name: Run tests
          command: npm test
      - run: yarn add -D webpack@latest webpack-cli@latest
      - run:
          name: Run tests w/ webpack@latest
          command: npm test
      - run:
          name: Semantic release
          command: npm run semantic-release || true
