default:
  cache_path: ".cy/cache"

development: &development
  api_url: "http://localhost:1234"

test:
  <<: *development
  cache_path: ".cy_test/cache"

production:
  api_url: "http://api.cypress.io"