default:
  cy_path: ".cy"
  cache_path: ".cy/#{process.env.CYPRESS_ENV}/cache"
  log_path: ".cy/#{process.env.CYPRESS_ENV}"
  s3:
    path: "https://s3.amazonaws.com"
    bucket: dist.cypress.io
    manifest: "manifest.json"

development: &development
  api_url: "http://localhost:1234"

test:
  <<: *development

production:
  api_url: "http://api.cypress.io"