default:
  cache_path: ".cy/cache"
  log_path: ".cy/logs"
  s3:
    path: "https://s3.amazonaws.com"
    bucket: dist.cypress.io
    manifest: "manifest.json"

development: &development
  api_url: "http://localhost:1234"

test:
  <<: *development
  cache_path: ".cy_test/cache"
  log_path: ".cy_test/logs"

production:
  api_url: "http://api.cypress.io"